version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: astra_ai_container
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/app/sonic-potion-417909-4df3012dc349.json
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8080"]