from enum import StrEnum


class NationalityISO3(StrEnum):
    """
    ISO3 standard codes for Nationalities.
    """
    UNKNOWN = "Unknown"

    AFG = "Afghan",
    ALB = "Albanian",
    DZA = "Algerian",
    AND = "Andorran",
    AGO = "Angolan",
    ARG = "Argentine",
    ARM = "Armenian",
    AUS = "Australian",
    AUT = "Austrian",
    AZE = "Azerbaijani",
    BHS = "Bahamian",
    BHR = "Bahraini",
    BGD = "Bangladeshi",
    BRB = "Barbadian",
    BLR = "Belarusian",
    BEL = "Belgian",
    BLZ = "Belizean",
    BEN = "Beninese",
    BTN = "Bhutanese",
    BOL = "Bolivian",
    BIH = "Bosnian",
    BWA = "Botswanan",
    BRA = "Brazilian",
    BRN = "Bruneian",
    BGR = "Bulgarian",
    BFA = "Burkinabé",
    BDI = "Burundian",
    KHM = "Cambodian",
    CMR = "Cameroonian",
    CAN = "Canadian",
    CPV = "Cape Verdean",
    CAF = "Central African",
    TCD = "Chadian",
    CHL = "Chilean",
    CHN = "Chinese",
    COL = "Colombian",
    COM = "Comoran",
    COG = "Congolese",
    COD = "Congolese",
    CRI = "Costa Rican",
    HRV = "Croatian",
    CUB = "Cuban",
    CYP = "Cypriot",
    CZE = "Czech",
    DNK = "Danish",
    DJI = "Djiboutian",
    DMA = "Dominican",
    DOM = "Dominican",
    ECU = "Ecuadorian",
    EGY = "Egyptian",
    SLV = "Salvadoran",
    GNQ = "Equatoguinean",
    ERI = "Eritrean",
    EST = "Estonian",
    SWZ = "Swazi",
    ETH = "Ethiopian",
    FJI = "Fijian",
    FIN = "Finnish",
    FRA = "French",
    GAB = "Gabonese",
    GMB = "Gambian",
    GEO = "Georgian",
    DEU = "German",
    GHA = "Ghanaian",
    GRC = "Greek",
    GRD = "Grenadian",
    GTM = "Guatemalan",
    GIN = "Guinean",
    GNB = "Bissau-Guinean",
    GUY = "Guyanese",
    HTI = "Haitian",
    HND = "Honduran",
    HUN = "Hungarian",
    ISL = "Icelandic",
    IND = "Indian",
    IDN = "Indonesian",
    IRN = "Iranian",
    IRQ = "Iraqi",
    IRL = "Irish",
    ISR = "Israeli",
    ITA = "Italian",
    JAM = "Jamaican",
    JPN = "Japanese",
    JOR = "Jordanian",
    KAZ = "Kazakh",
    KEN = "Kenyan",
    KIR = "I-Kiribati",
    PRK = "North Korean",
    KOR = "South Korean",
    KWT = "Kuwaiti",
    KGZ = "Kyrgyz",
    LAO = "Laotian",
    LVA = "Latvian",
    LBN = "Lebanese",
    LSO = "Basotho",
    LBR = "Liberian",
    LBY = "Libyan",
    LIE = "Liechtensteiner",
    LTU = "Lithuanian",
    LUX = "Luxembourgish",
    MDG = "Malagasy",
    MWI = "Malawian",
    MYS = "Malaysian",
    MDV = "Maldivian",
    MLI = "Malian",
    MLT = "Maltese",
    MHL = "Marshallese",
    MRT = "Mauritanian",
    MUS = "Mauritian",
    MEX = "Mexican",
    FSM = "Micronesian",
    MDA = "Moldovan",
    MCO = "Monegasque",
    MNG = "Mongolian",
    MNE = "Montenegrin",
    MAR = "Moroccan",
    MOZ = "Mozambican",
    MMR = "Burmese",
    NAM = "Namibian",
    NRU = "Nauruan",
    NPL = "Nepalese",
    NLD = "Dutch",
    NZL = "New Zealander",
    NIC = "Nicaraguan",
    NER = "Nigerien",
    NGA = "Nigerian",
    MKD = "Macedonian",
    NOR = "Norwegian",
    OMN = "Omani",
    PAK = "Pakistani",
    PLW = "Palauan",
    PAN = "Panamanian",
    PNG = "Papua New Guinean",
    PRY = "Paraguayan",
    PER = "Peruvian",
    PHL = "Filipino",
    POL = "Polish",
    PRT = "Portuguese",
    QAT = "Qatari",
    ROU = "Romanian",
    RUS = "Russian",
    RWA = "Rwandan",
    KNA = "Kittitian or Nevisian",
    LCA = "Saint Lucian",
    VCT = "Vincentian",
    WSM = "Samoan",
    SMR = "San Marinese",
    STP = "São Toméan",
    SAU = "Saudi",
    SEN = "Senegalese",
    SRB = "Serbian",
    SYC = "Seychellois",
    SLE = "Sierra Leonean",
    SGP = "Singaporean",
    SVK = "Slovak",
    SVN = "Slovene",
    SLB = "Solomon Islander",
    SOM = "Somali",
    ZAF = "South African",
    SSD = "South Sudanese",
    ESP = "Spanish",
    LKA = "Sri Lankan",
    SDN = "Sudanese",
    SUR = "Surinamese",
    SWE = "Swedish",
    CHE = "Swiss",
    SYR = "Syrian",
    TWN = "Taiwanese",
    TJK = "Tajik",
    TZA = "Tanzanian",
    THA = "Thai",
    TLS = "Timorese",
    TGO = "Togolese",
    TON = "Tongan",
    TTO = "Trinidadian or Tobagonian",
    TUN = "Tunisian",
    TUR = "Turkish",
    TKM = "Turkmen",
    TUV = "Tuvaluan",
    UGA = "Ugandan",
    UKR = "Ukrainian",
    ARE = "Emirati",
    GBR = "British",
    USA = "American",
    URY = "Uruguayan",
    UZB = "Uzbek",
    VUT = "Ni-Vanuatu",
    VEN = "Venezuelan",
    VNM = "Vietnamese",
    YEM = "Yemeni",
    ZMB = "Zambian",
    ZWE = "Zimbabwean"


class CountryISO3(StrEnum):
    """
    ISO3 standard codes for Countries.
    """
    UNKNOWN = "Unknown"

    AFG = "Afghanistan"
    ALB = "Albania"
    DZA = "Algeria"
    AND = "Andorra"
    AGO = "Angola"
    ARG = "Argentina"
    ARM = "Armenia"
    AUS = "Australia"
    AUT = "Austria"
    AZE = "Azerbaijan"
    BHS = "Bahamas"
    BHR = "Bahrain"
    BGD = "Bangladesh"
    BRB = "Barbados"
    BLR = "Belarus"
    BEL = "Belgium"
    BLZ = "Belize"
    BEN = "Benin"
    BTN = "Bhutan"
    BOL = "Bolivia"
    BIH = "Bosnia and Herzegovina"
    BWA = "Botswana"
    BRA = "Brazil"
    BRN = "Brunei"
    BGR = "Bulgaria"
    BFA = "Burkina Faso"
    BDI = "Burundi"
    KHM = "Cambodia"
    CMR = "Cameroon"
    CAN = "Canada"
    CPV = "Cape Verde"
    TCD = "Chad"
    CHL = "Chile"
    CHN = "China"
    COL = "Colombia"
    COM = "Comoros"
    COD = "Congo (Democratic Republic)"
    COG = "Congo (Republic)"
    CRI = "Costa Rica"
    CIV = "Côte d'Ivoire"
    HRV = "Croatia"
    CUB = "Cuba"
    CYP = "Cyprus"
    CZE = "Czech Republic"
    DNK = "Denmark"
    DJI = "Djibouti"
    DMA = "Dominica"
    DOM = "Dominican Republic"
    ECU = "Ecuador"
    EGY = "Egypt"
    SLV = "El Salvador"
    GNQ = "Equatorial Guinea"
    ERI = "Eritrea"
    EST = "Estonia"
    ETH = "Ethiopia"
    FJI = "Fiji"
    FIN = "Finland"
    FRA = "France"
    GAB = "Gabon"
    GMB = "Gambia"
    GEO = "Georgia"
    DEU = "Germany"
    GHA = "Ghana"
    GRC = "Greece"
    GRD = "Grenada"
    GTM = "Guatemala"
    GIN = "Guinea"
    GNB = "Guinea-Bissau"
    GUY = "Guyana"
    HTI = "Haiti"
    HND = "Honduras"
    HUN = "Hungary"
    ISL = "Iceland"
    IND = "India"
    IDN = "Indonesia"
    IRN = "Iran"
    IRQ = "Iraq"
    IRL = "Ireland"
    ISR = "Israel"
    ITA = "Italy"
    JAM = "Jamaica"
    JPN = "Japan"
    JOR = "Jordan"
    KAZ = "Kazakhstan"
    KEN = "Kenya"
    KIR = "Kiribati"
    KWT = "Kuwait"
    KGZ = "Kyrgyzstan"
    LAO = "Laos"
    LVA = "Latvia"
    LBN = "Lebanon"
    LSO = "Lesotho"
    LBR = "Liberia"
    LBY = "Libya"
    LIE = "Liechtenstein"
    LTU = "Lithuania"
    LUX = "Luxembourg"
    MDG = "Madagascar"
    MWI = "Malawi"
    MYS = "Malaysia"
    MDV = "Maldives"
    MLI = "Mali"
    MLT = "Malta"
    MRT = "Mauritania"
    MUS = "Mauritius"
    MEX = "Mexico"
    MDA = "Moldova"
    MCO = "Monaco"
    MNG = "Mongolia"
    MNE = "Montenegro"
    MAR = "Morocco"
    MOZ = "Mozambique"
    MMR = "Myanmar"
    NAM = "Namibia"
    NPL = "Nepal"
    NLD = "Netherlands"
    NZL = "New Zealand"
    NIC = "Nicaragua"
    NER = "Niger"
    NGA = "Nigeria"
    PRK = "North Korea"
    MKD = "North Macedonia"
    NOR = "Norway"
    OMN = "Oman"
    PAK = "Pakistan"
    PAN = "Panama"
    PNG = "Papua New Guinea"
    PRY = "Paraguay"
    PER = "Peru"
    PHL = "Philippines"
    POL = "Poland"
    PRT = "Portugal"
    QAT = "Qatar"
    ROU = "Romania"
    RUS = "Russia"
    RWA = "Rwanda"
    KNA = "Saint Kitts and Nevis"
    LCA = "Saint Lucia"
    VCT = "Saint Vincent and the Grenadines"
    WSM = "Samoa"
    SMR = "San Marino"
    STP = "Sao Tome and Principe"
    SAU = "Saudi Arabia"
    SEN = "Senegal"
    SRB = "Serbia"
    SYC = "Seychelles"
    SLE = "Sierra Leone"
    SGP = "Singapore"
    SVK = "Slovakia"
    SVN = "Slovenia"
    SLB = "Solomon Islands"
    SOM = "Somalia"
    ZAF = "South Africa"
    KOR = "South Korea"
    SSD = "South Sudan"
    ESP = "Spain"
    LKA = "Sri Lanka"
    SDN = "Sudan"
    SUR = "Suriname"
    SWE = "Sweden"
    CHE = "Switzerland"
    SYR = "Syria"
    TWN = "Taiwan"
    TJK = "Tajikistan"
    TZA = "Tanzania"
    THA = "Thailand"
    TLS = "Timor-Leste"
    TGO = "Togo"
    TON = "Tonga"
    TTO = "Trinidad and Tobago"
    TUN = "Tunisia"
    TUR = "Turkey"
    TKM = "Turkmenistan"
    TUV = "Tuvalu"
    UGA = "Uganda"
    UKR = "Ukraine"
    ARE = "United Arab Emirates"
    GBR = "United Kingdom"
    USA = "United States of America"
    URY = "Uruguay"
    UZB = "Uzbekistan"
    VUT = "Vanuatu"
    VEN = "Venezuela"
    VNM = "Vietnam"
    YEM = "Yemen"
    ZMB = "Zambia"
    ZWE = "Zimbabwe"


class APIStatus(StrEnum):
    UNKNOWN = "Unknown"
    SUCCESS = "Success"
    FAILED = "Failed"


class Gender(StrEnum):
    UNKNOWN = "Unknown"

    MALE = "Male"
    FEMALE = "Female"


class IdentityDocumentType(StrEnum):
    UNKNOWN = "Unknown"

    PASSPORT = "Passport"
    CNIC = "CNIC"
